# Generated by Django 3.2.9 on 2022-01-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatodo',
            name='style_todo',
            field=models.CharField(max_length=200, null=True, verbose_name='Стиль'),
        ),
    ]
