# Generated by Django 3.2.9 on 2022-01-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_datatodo_style_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatodo',
            name='style_todo',
            field=models.CharField(default='', max_length=200, verbose_name='Стиль'),
        ),
    ]
